server:
  port: 8080

spring:
  application:
    name: redis-demo
  redis:
    host: localhost
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
logging:
  level:
    root: info
    com:
      ningdr:
        redis:
          redisdemo: debug
